Repository trypear/pear-landing-page, pull requests merged in 2024-08, with the labels that each got.

#194 fix decoding/encoding callback (was fixed in #178 but was re-introduced)
  components/settings.tsx
Labels: bug fix

#193 Changes for small devices and other small fixes
  components/features.tsx
  components/hero.tsx
Labels: bug fix

#197 Add Geist Typeface to Project
  app/layout.tsx
  components/features.tsx
  package-lock.json
  package.json
  tailwind.config.js
  yarn.lock
Labels: enhancement

#195 restructured footer
  app/(default)/layout.tsx
  components/footer.tsx
  components/privacy-policy.tsx
  components/terms-of-service.tsx
Labels: enhancement

#198 fix: remove "next/head" from app directory
  app/not-found.tsx
Labels: bug fix

#199 perf: Optimize internal navigation using Nextjs Link components
  app/priority-waitlist/page.tsx
  components/pricing.tsx
  components/privacy-policy.tsx
  components/terms-of-service.tsx
Labels: enhancement, bug fix

#201 chore: changelog v0.0.2
  app/changelog/changelog.tsx
  app/changelog/page.tsx
  app/changelog/timeline.tsx
  public/images/includeFile - v.0.0.2.png
  public/images/shortcutBar- v.0.0.2.png
Labels: documentation, enhancement

#202 Settings Page Revamp
  app/(auth)/actions.ts
  app/(auth)/auth/callback/route.ts
  app/(auth)/auth/confirm/route.ts
  app/(auth)/signin/page.tsx
  app/dashboard/page.tsx
  components/auth/signup.tsx
  components/dashboard.tsx
  components/dashboard/freetrial-card.tsx
  components/dashboard/profile-card.tsx
  components/dashboard/subscription-card.tsx
  components/pricing-success.tsx
  components/settings.tsx
  components/ui/authbutton.tsx
  components/ui/mobile-menu.tsx
  components/ui/progress.tsx
  hooks/useCancelSubscription.ts
  package.json
  yarn.lock
Labels: enhancement

#200 Added FAQ Page
  app/faq/page.tsx
  components/footer.tsx
  components/ui/accordion.tsx
  components/ui/mobile-menu.tsx
  components/ui/navLink.tsx
  package-lock.json
  package.json
  types/faqItems.ts
  utils/constants.ts
  yarn.lock
Labels: enhancement

#207 Spelling mistake on FAQ page
  app/faq/page.tsx
Labels: bug fix

#205 Pricings redesign: Added early-bird and free-trial options
  app/globals.css
  components/pricing.tsx
  components/ui/badge.tsx
  components/ui/card.tsx
  components/ui/icons.tsx
  public/icons/mac icon.svg
  public/icons/win icon.svg
  tailwind.config.js
  types/pricing.ts
  utils/constants.ts
  yarn.lock
Labels: enhancement

#222 Oauth form fix
  components/auth/signin.tsx
  components/auth/signup.tsx
Labels: bug fix

#220 Added disclaimer to "Open PearAI" button
  components/dashboard/freetrial-card.tsx
Labels: documentation, enhancement

#223 style: make faq page bigger
  app/faq/page.tsx
Labels: enhancement

#235 twitter-image-optimization
  components/about.tsx
  components/tweet.tsx
  components/ui/my-tweet.tsx
  next.config.js
Labels: bug fix

#237 feat(footer): add Twitter handle
  .eslintrc.json
  components/ui/icons.tsx
  package.json
  utils/constants.ts
Labels: documentation, enhancement

#236 fix: changelog page UI flickering
  app/changelog/changelog.tsx
  app/changelog/timeline.tsx
Labels: bug fix

#204 chore: changelog v0.0.3
  app/changelog/changelog.tsx
  public/images/hero-image-01.jpg
  public/images/includeFile - v.0.0.2.png
  public/images/includeFile - v0.0.1.png
  public/images/modelSwitch- v0.0.3.png
  public/images/shortcutBar- v.0.0.2.png
  public/images/shortcutBar- v0.0.2.png
Labels: documentation

#221 Navbar redesign
  components/dashboard.tsx
  components/ui/PearGreen.svg
  components/ui/authbutton.tsx
  components/ui/header.tsx
  components/ui/mobile-menu.tsx
  components/ui/navigation-menu.tsx
  components/ui/sheet.tsx
  package.json
  utils/constants.ts
  yarn.lock
Labels: enhancement, help wanted

#244 feat: add confetti on countdown (i hope this works)
  components/countdown.tsx
  components/hero.tsx
  package.json
  yarn.lock
Labels: enhancement

#241 youtube-embed
  components/features.tsx
  components/ui/YoutubeEmbed.tsx
Labels: enhancement
