Repository trypear/pear-landing-page, pull requests merged in 2024-06, with the labels that each got.

#43 Landing page revamp and basic color scheme changes
  app/css/additional-styles/utility-patterns.css
  app/css/style.css
  app/globals.css
  app/layout.tsx
  components/about.tsx
  components/auth/reset-password.tsx
  components/auth/signin.tsx
  components/auth/signup.tsx
  components/features.tsx
  components/hero.tsx
  components/newsletter.tsx
  components/try.tsx
  components/ui/PearDark26x24.svg
  components/ui/PearHeroLogo.svg
  components/ui/PearPrimary70x70.svg
  components/ui/aspect-ratio.tsx
  components/ui/authbutton.tsx
  components/ui/footer.tsx
  components/ui/header.tsx
  components/ui/mobile-menu.tsx
  components/ui/slider.tsx
  components/ui/switch.tsx
  package.json
  public/gifs/pearai-@file.gif
  public/gifs/pearai-CMD+I.gif
  public/gifs/pearai-CMD+L2.gif
  tailwind.config.js
  yarn.lock
Labels: enhancement

#63 update mobile menu buttons to new styling
  components/ui/mobile-menu.tsx
Labels: enhancement

#46 chore(readme): update readme
  README.md
Labels: documentation

#78 fix transition bug on hero button
  components/hero.tsx
Labels: enhancement

#75 fix fade-in, fix navbar being too big, and fixed features ui in smaller screens
  components/features.tsx
  components/ui/header.tsx
Labels: bug

#83 bug fix - sign out form action was removed unknowingly
  components/ui/authbutton.tsx
Labels: bug fix

#70 make hero title text bigger
  components/hero.tsx
Labels: enhancement

#69 update favicon to use the updated logo
  public/favicon.ico
Labels: enhancement

#87 fix deployment - prettier hero
  components/hero.tsx
Labels: bug fix

#60 change `.env.local.example` for easier setup
  .env.local.example
Labels: documentation

#92 signin/signup/reset-password pages now consistent with color scheme
  app/css/additional-styles/utility-patterns.css
  components/auth/reset-password.tsx
  components/auth/signin.tsx
  components/auth/signup.tsx
  components/ui/mobile-menu.tsx
Labels: bug fix

#91 Fix footer links alignment and spacing for mobile screens
  components/ui/footer.tsx
Labels: bug fix

#89 FEAT: Added husky precommit hooks
  .eslintrc.json
  .husky/pre-commit
  package.json
  yarn.lock
Labels: enhancement

#82 Navbar styling changes
  .eslintrc.json
  components/ui/PearDark.svg
  components/ui/PearDark26x24.svg
  components/ui/header.tsx
  components/ui/mobile-menu.tsx
Labels: enhancement

#101 refactor folders to remove redundancy
  app/about/page.tsx
  app/privacy/page.tsx
  app/private/page.tsx
  app/settings/layout.tsx
  app/settings/page.tsx
Labels: enhancement

#93 Add issue and pull request templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#102 feat(auth): Added form validations using Zod schema
  .github/ISSUE_TEMPLATE.md
  components/auth/reset-password.tsx
  components/auth/signin.tsx
  components/auth/signup.tsx
  components/ui/form.tsx
  package.json
  utils/form-schema.ts
  yarn.lock
Labels: enhancement, bug fix

#103 Settings page
  app/settings/page.tsx
  components/auth/reset-password.tsx
  components/auth/signin.tsx
  components/auth/signup.tsx
  components/hero.tsx
  components/try.tsx
  components/ui/button.tsx
  components/ui/mobile-menu.tsx
Labels: enhancement

#109 Add update password button to settings page
  app/settings/page.tsx
Labels: enhancement

#106 feat(pages): Pricing page
  app/pricing/page.tsx
  components/pricing.tsx
Labels: enhancement

#107 feat: add loading state to sign in, sign up, and reset password pages
  components/auth/reset-password.tsx
  components/auth/signin.tsx
  components/auth/signup.tsx
  components/ui/button.tsx
  components/ui/spinner.tsx
  tailwind.config.js
  utils/form-schema.ts
Labels: enhancement

#42 User Workflow Landing Page
  .env.local.example
  app/(auth)/actions.ts
  app/(auth)/auth/auth-code-error/page.tsx
  app/(auth)/auth/callback/route.ts
  app/(auth)/auth/confirm/route.ts
  app/layout.tsx
  app/settings/page.tsx
  components/auth/auth-error.tsx
  components/auth/signin.tsx
  components/auth/signup.tsx
  components/auth/update-password-form.tsx
  components/ui/header.tsx
  components/ui/icons.tsx
  components/ui/sonner.tsx
  middleware.ts
Labels: enhancement

#105 Added new page that tells user to confirm their email address after signup
  app/(auth)/actions.ts
  app/(auth)/verification/page.tsx
  components/auth/verification.tsx
Labels: enhancement
