Repository trypear/pear-landing-page, pull requests merged in 2024-07, with the labels that each got.

#124 Automate sign in from desktop pearai app
  app/(auth)/actions.ts
  app/(auth)/auth/callback/route.ts
  app/settings/page.tsx
  components/auth/signin.tsx
  components/settings.tsx
Labels: enhancement

#135 callback with access_token and refresh_token now carry on to settings page if user is logged in
  app/(auth)/signin/page.tsx
Labels: enhancement

#127 Fix/mobile menu items
  components/ui/header.tsx
  components/ui/mobile-menu.tsx
Labels: bug fix

#120 Fixing SEO stuffs + add route to sitemap
  app/sitemap.ts
  components/features.tsx
  components/hero.tsx
Labels: enhancement

#139 Add PostHog analytics tracking with dynamic page view capture
  .env.local.example
  app/PostHogPageView.tsx
  app/layout.tsx
  app/providers.tsx
  package.json
  yarn.lock
Labels: enhancement

#138 Clean verification page
  app/(auth)/layout.tsx
  app/(auth)/verification/page.tsx
Labels: bug fix

#133 Remove unused components and assets
  app/(default)/page.tsx
  components/banner.tsx
  components/blocks.tsx
  components/modal-video.tsx
  components/newsletter.tsx
  components/testimonials.tsx
  components/ui/PearLight16x16.svg
  components/ui/PearLight70x70.svg
  components/ui/PearPrimary70x70.svg
  components/ui/document.svg
  components/ui/icons.tsx
  components/zigzag.tsx
  public/images/features-03-image-01.png
  public/images/features-03-image-02.png
  public/images/features-03-image-03.png
  public/images/testimonial-01.jpg
  public/images/testimonial-02.jpg
  public/images/testimonial-03.jpg
  public/videos/video.mp4
Labels: enhancement

#132 removed deadCode
  components/hero.tsx
Labels: enhancement, bug fix

#152 Add capture_pageleave feature to posthog initialization
  app/providers.tsx
Labels: bug fix

#140 Add external link attributes to outgoing links. Also added external link icon to appropriate buttons on home page
  components/hero.tsx
  components/try.tsx
  components/ui/header.tsx
Labels: enhancement

#185 fix - typo in settings
  components/settings.tsx
Labels: enhancement
